#!/usr/bin/env bash
#BSUB -G ustruct
#BSUB -q pbatch
#BSUB -nnodes 1
#BSUB -W 12:00


# #jsrun -r 1 
# python main.py --dim 3 \

python NPS/train_stochastic.py \
  --model stochastic_CHE --dim=3 --jobid LJ25 \
  --model_setting '{"G0":1,"G1":0,"G2":0}' \
  --frame_shape=25 --n_feats 128 \
  --f1 0.1 --loss "L2" --periodic \
  --datatype longclip --dir_data $HOME/data/LJ25 \
  --print_every=10 --test_every=10 \
  --epochs 20 --minibatch_size=100 --total_length 2 --lr=1e-2
exit

python NPS/train_stochastic.py \
  --model stochastic_CHE --dim=3 --jobid LJ25 \
  --model_setting '{"G0":1,"G1":0,"G2":0}' \
  --frame_shape=25 --n_feats 128 \
  --f1 0.1 --loss "L2" --periodic \
  --datatype longclip --dir_data $HOME/data/LJ25 \
  --print_every=10 --test_every=10 \
  --epochs 20 --minibatch_size=100 --lr=1e-2 \
  --total_length=20 --clip_step=10 --test_only
